### ISSUE TITLE
Filter rarely used words

### ISSUE THREAD

**Issue by kootenpv** [Conchylicultor/DeepQA#29] opened 2016-12-17 12:51 UTC
Even with some default params, P2 AWS instance seems to have trouble with maxLength 20 for example (all else default).

I thought: I'll lower batchSize, but it is only at 10? 10 is not a lot is it?

Did anyone try GPU?

**Comment by Conchylicultor** [comment] 2016-12-17 16:16
The problem is probably the memory used with the vocabulary size and the hidden size. Indeed the RNN output is projected into the vocabulary space so on the last linear layer you need to have a massive vocab_size * hidden_size matrix.

With sentence length=20, you'll have a bigger vocabulary size and the GPU memory on the Amazon instance is probably limited.

One fix could be to only keep the words which appears more than once. That should reduce the vocabulary size and also speed up the training.

**Comment by eschnou** [comment] 2016-12-18 20:58
@kootenpv I'm not sure about your issue. However I can confirm that it works with GPU. I could run it on my local desktop machine and use the GPU. (Win 8.1 x84 Nvidia GeForce 760). I haven't tried on Amazon p.x instances yet. On my local system, running 30 epoch with all default settings took about 12 hours.

**Comment by kootenpv** [comment] 2016-12-18 22:53
@Conchylicultor Thanks for the reply, that really makes sense! Training on CPU really works a lot better when we increase the batchSize. And indeed, I just filtered the words only occurring once and everything went a lot smoother.

@eschnou Default params, but my own dataset. @Conchylicultor was spot on.

**Comment by Conchylicultor** [comment] 2016-12-19 00:15
@kootenpv Thank you for the update. I'll correct that when I'll have more time.

**Comment by Conchylicultor** [comment] 2017-03-19 06:21
Fixed with #89

**Closed by Conchylicultor** 2017-03-19 06:21 UTC
